- http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/
- https://clairelegoues.com/2016/08/23/things-i-keep-repeating-about-writing/
- http://sarahnadi.org/writing-papers/
